In [6]:
#Question 1:  How would you find the maximum value from the following list?
numbers = [2, 4, 6, 1, 3, 7]
# Find the maximum value
max_value = max(numbers)
#Print the max_value
max_value









7

In [15]:
# Question 2: How would you combine the following list of strings into a single string?
items = ["apple", "mango", "banana", "chips"]

#Concactenate the list into a single string separated by a comma
combined_string = ",".join(items)

#Print the combines_string
combined_string

'apple,mango,banana,chips'

In [21]:
#Scenario, You have a dictionary where the keys are names and the values are ages. You need to retrieve the age of a specific person.
#Question, How would you get the age of "Dev" from the following dictionary?

# example of dictionary with key as names and values as ages
ages = {"David": 25, "Christina": 55, "Dev":23, "Alisha":45}

#Get the age of "Dev"
Dev_age = ages["Dev"]

#Print Dev's age
Dev_age



23

In [29]:
# Scenario: You need to remove duplicate elements from a list while preserving the original order of elements.
#Question: How would you remove duplicates from the following list?

# list with duplicates

numbers = [1,2,3,4,5,7,8,3,2,4]
def remove_duplicates(input_list):
    seen = set()
    result = []
    for item in input_list:
        if item not in seen:
            seen.add(item)
            result.append(item)
    return result

#Remove duplicates
unique_numbers = remove_duplicates(numbers)

unique_numbers


[1, 2, 3, 4, 5, 7, 8]

In [37]:
#Scenario: You have a 2D NumPy array and need to get the maximum value from each column.
# Question: How would you find the maximum values for each column in the following array?

import numpy as np

# Example 2D NumPy array
array = np.array([
    [1, 3, 4],
    [7, 2, 5],
    [9, 8, 6]
])

# Find the maximum value for each column
max_values = np.amax(array, axis=0)
max_values


array([9, 8, 6])

In [45]:
#Scenario: You have a DataFrame and need to sort it by a specific column.
#Question: How would you sort the DataFrame by the "Age" column?

import pandas as pd

#Example database
data = { 
    "Name" : ["Harry", "Bob", "Rosyln", "Isabella", "Eva"],
    "Age": [23, 34, 62, 38, 12],
    "City": ["Kathmandu", "Miami", "New York", "Chicago", "Baltimore"]
}
df = pd.DataFrame(data)
# Sort the DataFrame by the "Age" column
sorted_df = df.sort_values(by="Age")

# Print the sorted DataFrame
print(sorted_df)
    




       Name  Age       City
4       Eva   12  Baltimore
0     Harry   23  Kathmandu
1       Bob   34      Miami
3  Isabella   38    Chicago
2    Rosyln   62   New York


In [79]:
#ScenarioYou need to calculate the total sum of a column in a DataFrame.
#Question: How would you find the sum of the "Sales" column?

import pandas as pd

data = {
    "Product": ["A", "B", "C", "D"],
    "Sales": [150, 200, 300, 250]
}
df = pd.DataFrame(data)
#Sum of the sales column 
total_sales = df["Sales"].sum()
total_sales
    

900

In [83]:
#Scenario: You need to check if a variable is of type int.
# Question: How would you verify if a variable x is an integer?

# Example variable
x = 32

# Check if x is an integer
is_integer = isinstance(x, int)

# Print the result
if is_integer:
    print("x is an integer.")
else:
    print("x is not an integer.")


x is an integer.


In [105]:
#Scenario: You have a list of mixed types and need to create separate lists for integers, floats, and strings.
#Question: How would you categorize the following mixed list into different types?

# Example of mixed list
mixed_list = [2, "banana", 2.5, 21, "mango", 1.5, "cherry", 56]

#separate lists for different types
integers = []
strings = []
floats = []

#Categorize the elements
for item in mixed_list:
    if isinstance(item, int):
        integers.append(item)
    elif isinstance(item, float):
        floats.append(item)
    elif isinstance(item, str):
        strings.append(item)

print("Integers:", integers)
print("Floats:", floats)
print("Strings:", strings)

Integers: [2, 21, 56]
Floats: [2.5, 1.5]
Strings: ['banana', 'mango', 'cherry']


In [118]:
#Scenario: You are given a string of comma-separated numbers. You need to convert this string into a list of integers.
#Question: How would you achieve this conversion?
#Example string of comma separated numbers
number_string = "2,5,6,3,5,7,9,11,12"

#Split the strings into a list of strings
string_list = number_string.split(",")

#convert the list of strings into list of integers
integer_list = list(map(int, string_list))

integer_list





[2, 5, 6, 3, 5, 7, 9, 11, 12]

In [122]:
#Scenario: You need to reverse the words in a sentence while keeping the order of the words intact.
#Question: How would you reverse each word in the following sentence?

#Example Sentence
sentence = "Do not worry be happy"

#Split the sentence into a list of words
words = sentence. split()

#Reverse each word
reversed_words = [word [::-1] for word in words]

#join the reversed word back into the sentence 
reversed_sentence = " ".join(reversed_words)

reversed_sentence


'oD ton yrrow eb yppah'

In [124]:
#Scenario: You need to combine two lists into a dictionary where the elements of the first list are keys and the elements of the second list are values.
#Question: How would you combine the following lists into a dictionary?
#Example list 
keys = ["name", "age", "city"]
values = ["Alex", "45", "Kathmandu"]
#Combine the list into a dictionary
combined_dict = dict(zip(keys, values))
combined_dict

{'name': 'Alex', 'age': '45', 'city': 'Kathmandu'}

In [130]:
#Scenario: You are given a list of tuples where each tuple contains a name and an age. You need to sort this list by age.
#Question: How would you sort the following list of tuples by age?

#Example list of tuple
people = [("Anna", 30), ("Bob", 32), ("Sally", 35), ("Bella", 23), ("Justin", 43)]

#sort list by age
sorted_people = sorted(people, key=lambda person: person[1])
sorted_people


[('Bella', 23), ('Anna', 30), ('Bob', 32), ('Sally', 35), ('Justin', 43)]

In [136]:
#Scenario: You have a 2D NumPy array and need to calculate the mean value of each row.
#Question: How would you compute the mean value for each row in the following array?

import numpy as np

#Example 2D numPy array 
array = np.array([
    [11,2,3],
    [5,9,8],
    [6,7,4]
])

#Calculate the mean value for each row
mean_row = np.mean(array, axis=1)
mean_row



array([5.33333333, 7.33333333, 5.66666667])

In [138]:
#Scenario: You need to create a NumPy array of size 10 filled with zeros, and then set the fifth element to 5.
#Question: How would you create and modify the array as described?

import numpy as np
#Create a numpy of size 10 filled with zeros
array = np.zeros(10)

#Set the fifth element(index 4) to 5
array[4]= 5

array

array([0., 0., 0., 0., 5., 0., 0., 0., 0., 0.])

In [154]:
#Scenario: You have a DataFrame and need to find the median of a numeric column.
#Question: How would you find the median of the "Scores" column in the following DataFrame?
import pandas as pd
#Example Dataframe
data = {
    "Name": ["Alice", "Bob", "Charlie", "Dev", "Eve"],
    "Scores": [88, 92, 85, 79, 94]
}

df = pd.DataFrame(data)

# Find the median of the "scores" column
median_score = df["Scores"].median()
median_score




88.0

In [156]:
#Scenario: You need to filter rows where the value in the "Sales" column is above 100 and then sort these rows by "Date" in descending order.
#Question: How would you filter and sort the DataFrame based on the given criteria?

import pandas as pd

#Example dataframe
data = {
    "Date": ["2024-01-01", "2024-01-02", "2024-01-03", "2024-01-04", "2024-01-05"],
    "Sales": [150, 80, 200, 50, 120]
}
df = pd.DataFrame(data)

#filter rows where "Sales" > 100
filtered_df = df[df["Sales"] > 100]

#Sort the filtered rows by 'Date' in descending order
sorted_df = filtered_df.sort_values(by="Date", ascending=False)

sorted_df


Date  Sales
4  2024-01-05    120
2  2024-01-03    200
0  2024-01-01    150

In [158]:
#Scenario: You have a string containing a number and need to convert it to an integer. Additionally, handle the case where the string might not represent a valid integer.
#Question: How would you safely convert the string "42" to an integer and handle invalid cases?

# Example string
number_string = "42"  

# Safely convert the string to an integer
try:
    number = int(number_string)
    print(f"Converted integer: {number}")
except ValueError:
    print("The string does not represent a valid integer.")



Converted integer: 42


In [ ]:
#Scenario: You have a list containing different data types, and you want to separate out all the strings.
#Question: How would you extract all string elements from the following list?

# Example list with different data types
mixed_list = [1, "hello", 3.14, "world", 42, "Python", True, None]

# Extract all string elements
string_elements = [item for item in mixed_list if isinstance(item, str)]
